#include "materials/uniform-material.h"
#include "materials/pattern-materials.h"
#include "materials/marble-material.h"
#include "materials/texture-material.h"
#include "materials/wood-material.h"
#include "materials/worley-material.h"