#include "pipeline/animation-processor.h"
#include "pipeline/renderer-processor.h"
#include "pipeline/motion-blur-processor.h"
#include "pipeline/wif-consumer.h"
#include "pipeline/overprint-processor.h"
#include "pipeline/inverter-processor.h"
#include "pipeline/pipeline-builder.h"