// Include all pipelines here
#include "pipeline/animation-processor.h"
#include "pipeline/renderer-processor.h"
#include "pipeline/motion-blur-processor.h"
#include "pipeline/wif-consumer.h"
#include "pipeline/wif-processor.h"
#include "pipeline/ppm-consumer.h"
#include "pipeline/bmp-consumer.h"
#include "pipeline/overprint-processor.h"
#include "pipeline/inverter-processor.h"
#include "pipeline/pipeline-builder.h"
#include "pipeline/null-consumer.h"
#include "pipeline/base64-processor.h"
#include "pipeline/text-writer-consumer.h"
#include "pipeline/studio-export-consumer.h"
