#include "demo/marble-animation-demo.h"
#include "demo/depth-of-field-demo.h"
#include "demo/fisheye-demo.h"
#include "demo/sphere-bumpifier-demo.h"
#include "demo/plane-bumpifier-demo.h"
#include "demo/split-depth-demo.h"
#include "demo/sampler-demo.h"
#include "demo/design-example.h"