cat test.chai | sed 's/SAMPLER/random(1)/' | /g/repos/ucll/3dcg/raytracer/raytracer/x64/Release/raytracer.exe -s - > random1.wif
cat test.chai | sed 's/SAMPLER/random(2)/' | /g/repos/ucll/3dcg/raytracer/raytracer/x64/Release/raytracer.exe -s - > random2.wif
cat test.chai | sed 's/SAMPLER/random(3)/' | /g/repos/ucll/3dcg/raytracer/raytracer/x64/Release/raytracer.exe -s - > random3.wif
cat test.chai | sed 's/SAMPLER/random(25)/' | /g/repos/ucll/3dcg/raytracer/raytracer/x64/Release/raytracer.exe -s - > random25.wif
cat test.chai | sed 's/SAMPLER/nrooks(1)/' | /g/repos/ucll/3dcg/raytracer/raytracer/x64/Release/raytracer.exe -s - > nrooks1.wif
cat test.chai | sed 's/SAMPLER/nrooks(2)/' | /g/repos/ucll/3dcg/raytracer/raytracer/x64/Release/raytracer.exe -s - > nrooks2.wif
cat test.chai | sed 's/SAMPLER/nrooks(3)/' | /g/repos/ucll/3dcg/raytracer/raytracer/x64/Release/raytracer.exe -s - > nrooks3.wif
cat test.chai | sed 's/SAMPLER/stratified(1,1)/' | /g/repos/ucll/3dcg/raytracer/raytracer/x64/Release/raytracer.exe -s - > stratified1-1.wif
cat test.chai | sed 's/SAMPLER/stratified(2,2)/' | /g/repos/ucll/3dcg/raytracer/raytracer/x64/Release/raytracer.exe -s - > stratified2-2.wif
cat test.chai | sed 's/SAMPLER/stratified(3,3)/' | /g/repos/ucll/3dcg/raytracer/raytracer/x64/Release/raytracer.exe -s - > stratified3-3.wif
cat test.chai | sed 's/SAMPLER/jittered(1,1)/' | /g/repos/ucll/3dcg/raytracer/raytracer/x64/Release/raytracer.exe -s - > jittered1-1.wif
cat test.chai | sed 's/SAMPLER/jittered(2,2)/' | /g/repos/ucll/3dcg/raytracer/raytracer/x64/Release/raytracer.exe -s - > jittered2-2.wif
cat test.chai | sed 's/SAMPLER/jittered(3,3)/' | /g/repos/ucll/3dcg/raytracer/raytracer/x64/Release/raytracer.exe -s - > jittered3-3.wif
cat test.chai | sed 's/SAMPLER/halfjittered(1,1)/' | /g/repos/ucll/3dcg/raytracer/raytracer/x64/Release/raytracer.exe -s - > halfjittered1-1.wif
cat test.chai | sed 's/SAMPLER/halfjittered(2,2)/' | /g/repos/ucll/3dcg/raytracer/raytracer/x64/Release/raytracer.exe -s - > halfjittered2-2.wif
cat test.chai | sed 's/SAMPLER/halfjittered(3,3)/' | /g/repos/ucll/3dcg/raytracer/raytracer/x64/Release/raytracer.exe -s - > halfjittered3-3.wif
cat test.chai | sed 's/SAMPLER/multijittered(1)/' | /g/repos/ucll/3dcg/raytracer/raytracer/x64/Release/raytracer.exe -s - > multijittered1.wif
cat test.chai | sed 's/SAMPLER/multijittered(2)/' | /g/repos/ucll/3dcg/raytracer/raytracer/x64/Release/raytracer.exe -s - > multijittered2.wif
cat test.chai | sed 's/SAMPLER/multijittered(3)/' | /g/repos/ucll/3dcg/raytracer/raytracer/x64/Release/raytracer.exe -s - > multijittered3.wif
cat test.chai | sed 's/SAMPLER/multijittered(5)/' | /g/repos/ucll/3dcg/raytracer/raytracer/x64/Release/raytracer.exe -s - > multijittered5.wif
