#pragma once

#include "primitives/primitive.h"
#include "primitives/cropper.h"
#include "primitives/disk.h"
#include "primitives/union.h"
#include "primitives/decorator.h"
#include "primitives/cylinder.h"
#include "primitives/sphere.h"
#include "primitives/intersection.h"
#include "primitives/plane.h"
#include "primitives/transformer.h"
#include "primitives/triangle.h"
#include "primitives/bounding-box-accelerator.h"
#include "primitives/mesh.h"
